export const ROUTE_MAIN = '/',
  ROUTE_SIGN_IN = '/sign-in',
  ROUTE_SIGN_UP = '/sign-up',
  ROUTE_PROFILE = '/profile',
  ROUTE_MOVIES = '/movies',
  ROUTE_SAVED_MOVIES = '/saved-movies',
  DEFAULT_MOVIES_KEY = 'allMovies',
  DEFAULT_MOVIES_URL = 'https://api.nomoreparties.co/',
  COUNT_BIG_SCREEN = 7,
  COUNT_SMALL_SCREEN = 5,
  STEP_BIG_SCREEN = 7,
  STEP_SMALL_SCREEN = 2,
  CHANGE_STEP_WIDTH = 481,
  CHANGE_HEADER_WIDTH = 768,
  SHORT_FILM_DURATION = 40,
  LOAD_MOVIES_ERROR_MESSAGE =
    'Во время запроса произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз.',
  TOKEN_ERROR_MESSAGE =
    'При авторизации произошла ошибка. Токен не передан или передан не в том формате.',
  SERVER_ERROR_MESSAGE = 'На сервере произошла ошибка.',
  TYPE_ERROR_MESSAGE = 'Кажется, что-то сломалось...',
  REGISTER_ERROR_MESSAGE = 'При регистрации произошла ошибка.',
  UPDATE_USER_ERROR_MESSAGE = 'При обновлении профиля произошла ошибка.';